INSERT INTO CLIENTS (NAME, LASTNAME) VALUES ('PEPE', 'DOE')
INSERT INTO CLIENTS (NAME, LASTNAME) VALUES ('MARIA', 'DOE')

INSERT INTO STUDENTS (NAME, LASTNAME) VALUES ('PEPO', 'DOE')
INSERT INTO STUDENTS (NAME, LASTNAME) VALUES ('PEPI', 'DOE')

INSERT INTO COURSES (NAME, INSTRUCTOR) VALUES ('Angular', 'Jose')
INSERT INTO COURSES (NAME, INSTRUCTOR) VALUES ('React', 'Jose')